# Generated by Django 4.2.17 on 2024-12-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fr_date', models.DateField(verbose_name='FR Date')),
                ('company_code', models.CharField(max_length=50, verbose_name='Company Code')),
                ('plant_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Plant Code')),
                ('vendor_name', models.CharField(max_length=255, verbose_name='Vendor Name')),
                ('vendor_code', models.CharField(max_length=50, verbose_name='Vendor Code')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('po_number', models.CharField(max_length=50, verbose_name='PO Number')),
                ('material_document_number', models.CharField(max_length=50, verbose_name='Material Document Number')),
                ('gl_account_number', models.CharField(max_length=50, verbose_name='GL Account Number')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
                ('invoice', models.CharField(max_length=50, verbose_name='Invoice')),
                ('invoice_dt', models.DateField(verbose_name='Invoice Date')),
                ('invoice_amt', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Invoice Amount')),
                ('tds', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='TDS')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sub Total')),
                ('fr_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='FR Amount')),
                ('approval1', models.CharField(default='waiting', max_length=50, verbose_name='Approval 1')),
                ('approval2', models.CharField(default='waiting', max_length=50, verbose_name='Approval 2')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
    ]
