# Generated by Django 4.2.17 on 2024-12-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comments',
            new_name='comments1',
        ),
    ]
