# Generated by Django 4.2.17 on 2024-12-19 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_comments_invoice_comments1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='comments1',
            new_name='commentsAPP1',
        ),
    ]
