# Generated by Django 4.2.17 on 2024-12-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_comments1_invoice_commentsapp1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='commentsAPP1',
            field=models.TextField(blank=True, null=True, verbose_name='CommentsAPP1'),
        ),
    ]
