# Generated by Django 4.2.17 on 2024-12-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_invoice_commentsapp1'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='commentsAPP2',
            field=models.TextField(blank=True, null=True, verbose_name='CommentsAPP2'),
        ),
    ]
